import type { CreateConfigValues } from "@paperclipai/adapter-utils";

export const defaultCreateValues: CreateConfigValues = {
  adapterType: "claude_local",
  cwd: "",
  instructionsFilePath: "",
  promptTemplate: "",
  model: "",
  provider: "",
  sessionNameTemplate: "",
  profileDirTemplate: "",
  allowedDomains: "",
  subcommand: "",
  subcommandArgs: "",
  targetUrlTemplate: "",
  stdinTemplate: "",
  promptToStdin: false,
  appendPromptAsArg: false,
  actionPolicyPath: "",
  contentBoundaries: false,
  maxOutput: 0,
  thinkingEffort: "",
  chrome: false,
  headed: false,
  dangerouslySkipPermissions: false,
  search: false,
  dangerouslyBypassSandbox: false,
  command: "",
  args: "",
  extraArgs: "",
  envVars: "",
  envBindings: {},
  url: "",
  bootstrapPrompt: "",
  maxTurnsPerRun: 80,
  heartbeatEnabled: false,
  intervalSec: 300,
};
